# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='city_name_en',
            field=models.CharField(default='test', max_length=80, verbose_name='\u0410\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0433\u043e\u0440\u043e\u0434\u0430'),
        ),
        migrations.AddField(
            model_name='cities',
            name='geo_latitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='geo_longitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
