# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0433\u043e\u0440\u043e\u0434\u0430')),
                ('city_name_en', models.CharField(max_length=80, unique=True, verbose_name='\u0410\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0433\u043e\u0440\u043e\u0434\u0430')),
                ('geo_latitude_min', models.FloatField(blank=True, default=0.0, null=True)),
                ('geo_latitude_max', models.FloatField(blank=True, default=0.0, null=True)),
                ('geo_longitude_min', models.FloatField(blank=True, default=0.0, null=True)),
                ('geo_longitude_max', models.FloatField(blank=True, default=0.0, null=True)),
                ('city_url', models.TextField(verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0433\u043e\u0440\u043e\u0434')),
                ('author', models.CharField(max_length=60, verbose_name='\u0410\u0432\u0442\u043e\u0440 \u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0439')),
            ],
            options={
                'ordering': ['city_name'],
                'db_table': 'cities',
                'verbose_name_plural': '\u0413\u043e\u0440\u043e\u0434\u0430',
            },
        ),
        migrations.CreateModel(
            name='CityPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.TextField(verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0444\u043e\u0442\u043e')),
                ('photo_path', models.TextField(verbose_name='\u041b\u043e\u043a\u0430\u043b\u044c\u043d\u044b\u0439 \u043f\u0443\u0442\u044c \u043a \u0444\u0430\u0439\u043b\u0443')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Cities', verbose_name='ID \u0413\u043e\u0440\u043e\u0434\u0430')),
            ],
            options={
                'db_table': 'city_photos',
                'verbose_name_plural': '\u0424\u043e\u0442\u043e \u0433\u043e\u0440\u043e\u0434\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='CityPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='\u041d\u0440\u0430\u0432\u0438\u0442\u0441\u044f/\u041d\u0435\u043d\u0440\u0430\u0432\u0438\u0442\u0441\u044f')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Cities', verbose_name='ID \u0413\u043e\u0440\u043e\u0434\u0430')),
            ],
            options={
                'db_table': 'city_polls',
                'verbose_name_plural': '\u0413\u043e\u043b\u043e\u0441\u043e\u0432\u0430\u043b\u043a\u0430 \u043f\u043e \u0433\u043e\u0440\u043e\u0434\u0430\u043c',
            },
        ),
        migrations.CreateModel(
            name='DialogStepRouting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(db_index=True, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u043e\u043d\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440 \u0447\u0430\u0442\u0430')),
                ('command', models.CharField(max_length=80, verbose_name='\u0422\u0435\u043a\u0443\u0449\u0430\u044f \u043a\u043e\u043c\u043c\u0430\u043d\u0434\u0430')),
                ('step', models.IntegerField(verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0448\u0430\u0433\u0430')),
            ],
            options={
                'db_table': 'dialog_step_routing',
                'verbose_name_plural': '\u0414\u0438\u0430\u043b\u043e\u0433\u0438 \u0441 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f\u043c\u0438',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='\u0418\u043c\u044f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f')),
                ('last_name', models.CharField(max_length=150, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f')),
                ('username', models.CharField(max_length=150, verbose_name='\u041b\u043e\u0433\u0438\u043d \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f')),
                ('chat_id', models.IntegerField(db_index=True, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u043e\u043d\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440 \u0447\u0430\u0442\u0430')),
            ],
            options={
                'db_table': 'user_info',
                'verbose_name_plural': '\u0421\u043f\u0438\u0441\u043e\u043a \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u0439',
            },
        ),
        migrations.AddField(
            model_name='citypoll',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.UserInfo', verbose_name='ID \u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f'),
        ),
        migrations.AddField(
            model_name='cities',
            name='city_prefer',
            field=models.ManyToManyField(through='bot.CityPoll', to='bot.UserInfo', verbose_name='\u0421\u0432\u044f\u0437\u044c \u0433\u043e\u0440\u043e\u0434\u043e\u0432 \u0441 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f\u043c\u0438'),
        ),
    ]
