# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20170316_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityphotos',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Cities', verbose_name='ID \u0433\u043e\u0440\u043e\u0434\u0430'),
        ),
        migrations.AlterField(
            model_name='citypoll',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Cities', verbose_name='ID \u0433\u043e\u0440\u043e\u0434\u0430'),
        ),
        migrations.AlterField(
            model_name='citypoll',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.UserInfo', verbose_name='ID \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f'),
        ),
        migrations.AlterModelTable(
            name='citypoll',
            table='city_poll',
        ),
    ]
