# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20170227_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='geo_latitude',
            new_name='geo_latitude_max',
        ),
        migrations.RenameField(
            model_name='cities',
            old_name='geo_longitude',
            new_name='geo_latitude_min',
        ),
        migrations.AddField(
            model_name='cities',
            name='geo_longitude_max',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='geo_longitude_min',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
