# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20170316_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='\u041d\u0440\u0430\u0432\u0438\u0442\u0441\u044f/\u041d\u0435\u043d\u0440\u0430\u0432\u0438\u0442\u0441\u044f')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Cities', verbose_name='ID \u0433\u043e\u0440\u043e\u0434\u0430')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.UserInfo', verbose_name='ID \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f')),
            ],
            options={
                'db_table': 'city_poll',
                'verbose_name_plural': '\u0413\u043e\u043b\u043e\u0441\u043e\u0432\u0430\u043b\u043a\u0430 \u043f\u043e \u0433\u043e\u0440\u043e\u0434\u0430\u043c',
            },
        ),
        migrations.AddField(
            model_name='cities',
            name='city_prefer',
            field=models.ManyToManyField(through='bot.CityPoll', to='bot.UserInfo', verbose_name='\u0421\u0432\u044f\u0437\u044c \u0433\u043e\u0440\u043e\u0434\u043e\u0432 \u0441 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f\u043c\u0438'),
        ),
    ]
